// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import faq_controller from "./home/faq_controller";
import shared_header_controller from "./shared/header_controller";

application.register("home--faq", faq_controller);
application.register("shared--header", shared_header_controller);
