# frozen_string_literal: true

module QuizThresholds
  DEFAULT_TAB_SWITCH_THRESHOLD = ENV.fetch('TAB_SWITCH_THRESHOLD', 5).to_i
  DEFAULT_COPY_PASTE_THRESHOLD = ENV.fetch('COPY_PASTE_THRESHOLD', 3).to_i
  DEFAULT_SCREENSHOT_THRESHOLD = ENV.fetch('SCREENSHOT_THRESHOLD', 1).to_i
  DEFAULT_DEVTOOLS_THRESHOLD = ENV.fetch('DEVTOOLS_THRESHOLD', 1).to_i
  DEFAULT_DEVICE_THRESHOLD = ENV.fetch('DEVICE_THRESHOLD', 2).to_i
end
